package mapreduce

import (
	"encoding/json"
	"hash/fnv"
	"io/ioutil"
	"log"
	"os"
)

func doMap(
	jobName string, // the name of the MapReduce job
	mapTask int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(filename string, contents string) []KeyValue,
) {

	//Step1: get key value pairs
	contents, err := ioutil.ReadFile(inFile)
	if err != nil {
		log.Fatal(err)
	}
	kvs := mapF(inFile, string(contents))

	//Step2: accumulate pairs with the same key:
	// { (a,1),(b,1),(a,1),(c,1),(a,1)... } -> { (a,[1,1,1]),(b,[1]),(c,[1])... }
	kvMap := make(map[string][]string)
	for _, kv := range kvs {
		s, _ := kvMap[kv.Key]
		kvMap[kv.Key] = append(s, kv.Value)
	}
	kvs = nil

	//Step3: send to Goroutines respectively
	//Use nReduce Goroutines to write the files
	//Work for every Goroutine: Read from channel, write to file
	kvChans := make([]chan map[string][]string, nReduce)
	for i := range kvChans {
		kvChans[i] = make(chan map[string][]string)
	}
	semaphoreChan := make(chan int)
	for i := 0; i < nReduce; i++ {
		fname := reduceName(jobName, mapTask, i)
		go invokeWriter(fname, kvChans[i], semaphoreChan)
	}

	for k, v := range kvMap {
		index := ihash(k) % nReduce
		kvChans[index] <- map[string][]string{k: v}
	}

	for i := range kvChans {
		close(kvChans[i])
	}

	//wait until all the Goroutines finish
	for i := 0; i < nReduce; i++ {
		<-semaphoreChan
	}
}

func invokeWriter(fname string, kvChan chan map[string][]string, semaphoreChan chan int) {
	//open file
	file, err := os.OpenFile(fname, os.O_CREATE|os.O_APPEND, 0644)
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	//read kv from channel and write to the file
	enc := json.NewEncoder(file)
	for kv := range kvChan {
		enc.Encode(&kv)
	}
	//send signal to main Goroutine
	semaphoreChan <- 1
}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}

//
// doMap manages one map task: it should read one of the input files
// (inFile), call the user-defined map function (mapF) for that file's
// contents, and partition mapF's output into nReduce intermediate files.
//
// There is one intermediate file per reduce task. The file name
// includes both the map task number and the reduce task number. Use
// the filename generated by reduceName(jobName, mapTask, r)
// as the intermediate file for reduce task r. Call ihash() (see
// below) on each key, mod nReduce, to pick r for a key/value pair.
//
// mapF() is the map function provided by the application. The first
// argument should be the input file name, though the map function
// typically ignores it. The second argument should be the entire
// input file contents. mapF() returns a slice containing the
// key/value pairs for reduce; see common.go for the definition of
// KeyValue.
//
// Look at Go's ioutil and os packages for functions to read
// and write files.
//
// Coming up with a scheme for how to format the key/value pairs on
// disk can be tricky, especially when taking into account that both
// keys and values could contain newlines, quotes, and any other
// character you can think of.
//
// One format often used for serializing data to a byte stream that the
// other end can correctly reconstruct is JSON. You are not required to
// use JSON, but as the output of the reduce tasks *must* be JSON,
// familiarizing yourself with it here may prove useful. You can write
// out a data structure as a JSON string to a file using the commented
// code below. The corresponding decoding functions can be found in
// common_reduce.go.
//
//   enc := json.NewEncoder(file)
//   for _, kv := ... {
//     err := enc.Encode(&kv)
//
// Remember to close the file after you have written all the values!
//
// Your code here (Part I).
//
