package main

import (
	"../mapreduce"
	"bytes"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func iiMapF(document string, value string) (res []mapreduce.KeyValue) {
	// Your code here (Part V).
	// split by non-alphabetic characters
	f := func(c rune) bool {
		return !unicode.IsLetter(c)
	}
	words := strings.FieldsFunc(value, f)
	kvMap := make(map[string]string)
	for _, w := range words {
		if _, ok := kvMap[w]; !ok {
			kvMap[w] = document
		}
	}
	kvs := make([]mapreduce.KeyValue, 0)
	for k, v := range kvMap {
		kvs = append(kvs, mapreduce.KeyValue{k, v})
	}
	return kvs
}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func iiReduceF(key string, values []string) string {
	// Your code here (Part V).
	sort.Strings(values)
	len := len(values)
	var buffer bytes.Buffer
	buffer.WriteString(strconv.Itoa(len))
	buffer.WriteString(" ")
	for i := 0; i < len; i++ {
		if i < len-1 {
			buffer.WriteString(values[i] + ",")
		} else {
			buffer.WriteString(values[i])
		}
	}
	return buffer.String()
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("iiseq", os.Args[3:], 3, iiMapF, iiReduceF)
		} else {
			mr = mapreduce.Distributed("iiseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], iiMapF, iiReduceF, 100, nil)
	}
}
