package main

import (
	"os"
	"strings"
	"unicode"
)
import "fmt"
import "mapreduce"

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func iiMapF(document string, value string) []mapreduce.KeyValue {
	f := func(ch rune) bool {
		return !unicode.IsLetter(ch)
	}
	words := strings.FieldsFunc(value, f)
	kvs := make([]mapreduce.KeyValue, len(words))
	wordSet := make(map[string]bool)
	for i, word := range words {
		if _, ok := wordSet[word]; !ok {
			kvs[i] = mapreduce.KeyValue{word, document}
			wordSet[word] = true
		}
	}
	return kvs
}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func iiReduceF(key string, values []string) string {
	if key == "" || key == "ACTRESS" {
		fmt.Println(">>> Find", key)
	}
	res := fmt.Sprintf("%d %s", len(values), strings.Join(values, ","))
	return res
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("iiseq", os.Args[3:], 3, iiMapF, iiReduceF)
		} else {
			mr = mapreduce.Distributed("iiseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], iiMapF, iiReduceF, 100, nil)
	}
}
